#!/bin/sh
# 系统基础配置

# 设置系统主机名
uci set system.@system[0].hostname='THDN-PrintServer'
uci set system.@system[0].description='THDN LEDE Print Server'
uci commit system

# 配置LAN网络
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.10.1'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway='192.168.10.1'
uci set network.lan.dns='8.8.8.8 114.114.114.114'
uci commit network

# 配置WiFi
uci set wireless.@wifi-device[0].disabled='0'
uci set wireless.@wifi-device[0].channel='6'
uci set wireless.@wifi-iface[0].mode='ap'
uci set wireless.@wifi-iface[0].ssid='THDN-dayin'
uci set wireless.@wifi-iface[0].encryption='psk2'
uci set wireless.@wifi-iface[0].key='thdn12345678'
uci set wireless.@wifi-iface[0].network='lan'
uci commit wireless

# 设置管理员密码 (admin/thdn12345678)
echo 'admin:$1$thdn1234$abcdefghijklmnopqrstuvwxyz123456:0:0:99999:7:::' >> /etc/shadow

# 配置DHCP
uci set dhcp.lan.start='100'
uci set dhcp.lan.limit='150'
uci set dhcp.lan.leasetime='12h'
uci set dhcp.lan.force='1'
uci commit dhcp

# 配置防火墙基本规则
uci set firewall.@zone[0].name='lan'
uci set firewall.@zone[0].network='lan'
uci set firewall.@zone[0].input='ACCEPT'
uci set firewall.@zone[0].output='ACCEPT'
uci set firewall.@zone[0].forward='ACCEPT'
uci commit firewall

# 删除自己
rm -f /etc/uci-defaults/10-system-basic
