#!/bin/sh
# LuCI CUPS模块权限配置

# 创建CUPS访问控制
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cups[-1]
	add ucitrack
	set ucitrack.@cups[-1].init=cups
	commit ucitrack
	
	delete system.ntp
	set system.ntp=timeserver
	set system.ntp.enabled='1'
	set system.ntp.enable_server='0'
	add_list system.ntp.server='0.openwrt.pool.ntp.org'
	add_list system.ntp.server='1.openwrt.pool.ntp.org'
	add_list system.ntp.server='2.openwrt.pool.ntp.org'
	add_list system.ntp.server='3.openwrt.pool.ntp.org'
	commit system
EOF

# 设置中文界面为默认
uci set luci.main.lang='zh_cn'
uci commit luci

# 删除自己
rm -f /etc/uci-defaults/50-cups-luci
