#!/bin/sh
# THDN打印服务器默认配置

# 设置主机名
uci set system.@system[0].hostname='THDN-PrintServer'
uci commit system

# 设置LAN IP为192.168.10.1
uci set network.lan.ipaddr='192.168.10.1'
uci set network.lan.proto='static'
uci commit network

# 设置WiFi
uci set wireless.@wifi-device[0].disabled='0'
uci set wireless.@wifi-iface[0].ssid='THDN-dayin'
uci set wireless.@wifi-iface[0].encryption='psk2'
uci set wireless.@wifi-iface[0].key='thdn12345678'
uci commit wireless

# 设置管理员密码
echo 'admin:$1$thdn1234$abcdefghijklmnopqrstuvwxyz123456:0:0:99999:7:::' >> /etc/shadow

# 启用CUPS服务
/etc/init.d/cups enable
/etc/init.d/cups start

# 设置定时重启（每周日凌晨3点）
echo '0 3 * * 0 reboot' >> /etc/crontabs/root
/etc/init.d/cron enable
/etc/init.d/cron start

# 设置USB打印机自动识别
/etc/init.d/hotplug2 enable

exit 0
